version: "3.5"

services:
  pubmed_knowledge_graph_db:
    container_name: pubmed_knowledge_graph_db
    restart: always
    image: mysql:8.0
    ports:
      - 3306
    expose:
      - 3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=pubmed_knowledge_graph_dev
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
